version: "3.8"
services:
  app:
    build: .
    container_name: ai_assistant_app
    ports:
      - "8000:8000"  
      - "8001:8001"  
      - "8501:8501" 
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite:///./data/ai_assistant.db
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./prompts:/app/prompts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

